class Autogenerated {
  List<Tarefas>? tarefas;
  List<Clientes>? clientes;

  Autogenerated({this.tarefas, this.clientes});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['tarefas'] != null) {
      tarefas = <Tarefas>[];
      json['tarefas'].forEach((v) {
        tarefas!.add(Tarefas.fromJson(v));
      });
    }
    if (json['clientes'] != null) {
      clientes = <Clientes>[];
      json['clientes'].forEach((v) {
        clientes!.add(Clientes.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (tarefas != null) {
      data['tarefas'] = tarefas!.map((v) => v.toJson()).toList();
    }
    if (clientes != null) {
      data['clientes'] = clientes!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Tarefas {
  String? id;
  String? titulo;
  bool? concluida;

  Tarefas({this.id, this.titulo, this.concluida});

  Tarefas.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    titulo = json['titulo'];
    concluida = json['concluida'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['titulo'] = titulo;
    data['concluida'] = concluida;
    return data;
  }
}

class Clientes {
  String? id;
  String? nome;

  Clientes({this.id, this.nome});

  Clientes.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    nome = json['nome'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['nome'] = nome;
    return data;
  }
}
